from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(verbose_name="Nationality", max_length=100,
                 choices = [

                    (b'AF' , b'Afghanistan' ),
                    (b'AX' , b'Aland Islands' ),
                    (b'AL' , b'Albania' ),
                    (b'DZ' , b'Algeria' ),
                    (b'AS' , b'American Samoa' ),
                    (b'AD' , b'Andorra' ),
                    (b'AO' , b'Angola' ),
                    (b'AI' , b'Anguilla' ),
                    (b'AQ' , b'Antarctica' ),
                    (b'AG' , b'Antigua and Barbuda' ),
                    (b'AR' , b'Argentina' ),
                    (b'AM' , b'Armenia' ),
                    (b'AW' , b'Aruba' ),
                    (b'AU' , b'Australia' ),
                    (b'AT' , b'Austria' ),
                    (b'AZ' , b'Azerbaijan' ),
                    (b'BS' , b'Bahamas' ),
                    (b'BH' , b'Bahrain' ),
                    (b'BD' , b'Bangladesh' ),
                    (b'BB' , b'Barbados' ),
                    (b'BY' , b'Belarus' ),
                    (b'BE' , b'Belgium' ),
                    (b'BZ' , b'Belize' ),
                    (b'BJ' , b'Benin' ),
                    (b'BM' , b'Bermuda' ),
                    (b'BT' , b'Bhutan' ),
                    (b'BO' , b'Bolivia' ),
                    (b'BA' , b'Bosnia and Herzegovina' ),
                    (b'BW' , b'Botswana' ),
                    (b'BV' , b'Bouvet Island' ),
                    (b'BR' , b'Brazil' ),
                    (b'IO' , b'British Indian Ocean Territory' ),
                    (b'BN' , b'Brunei Darussalam' ),
                    (b'BG' , b'Bulgaria' ),
                    (b'BF' , b'Burkina Faso' ),
                    (b'BI' , b'Burundi' ),
                    (b'KH' , b'Cambodia' ),
                    (b'CM' , b'Cameroon' ),
                    (b'CA' , b'Canada' ),
                    (b'CV' , b'Cape Verde' ),
                    (b'KY' , b'Cayman Islands' ),
                    (b'CF' , b'Central African Republic' ),
                    (b'TD' , b'Chad' ),
                    (b'CL' , b'Chile' ),
                    (b'CN' , b'China' ),
                    (b'CX' , b'Christmas Island' ),
                    (b'CC' , b'Cocos Keeling Islands' ),
                    (b'CO' , b'Colombia' ),
                    (b'KM' , b'Comoros' ),
                    (b'CG' , b'Congo' ),
                    (b'CD' , b'Congo, The Democratic Republic of The' ),
                    (b'CK' , b'Cook Islands' ),
                    (b'CR' , b'Costa Rica' ),
                    (b'CI' , b'Cote D ivoire' ),
                    (b'HR' , b'Croatia' ),
                    (b'CU' , b'Cuba' ),
                    (b'CY' , b'Cyprus' ),
                    (b'CZ' , b'Czechia' ),
                    (b'DK' , b'Denmark' ),
                    (b'DJ' , b'Djibouti' ),
                    (b'DM' , b'Dominica' ),
                    (b'DO' , b'Dominican Republic' ),
                    (b'EC' , b'Ecuador' ),
                    (b'EG' , b'Egypt' ),
                    (b'SV' , b'El Salvador' ),
                    (b'GQ' , b'Equatorial Guinea' ),
                    (b'ER' , b'Eritrea' ),
                    (b'EE' , b'Estonia' ),
                    (b'ET' , b'Ethiopia' ),
                    (b'FK' , b'Falkland Islands' ),
                    (b'FO' , b'Faroe Islands' ),
                    (b'FJ' , b'Fiji' ),
                    (b'FI' , b'Finland' ),
                    (b'FR' , b'France' ),
                    (b'GF' , b'French Guiana' ),
                    (b'PF' , b'French Polynesia' ),
                    (b'TF' , b'French Southern Territories' ),
                    (b'GA' , b'Gabon' ),
                    (b'GM' , b'Gambia' ),
                    (b'GE' , b'Georgia' ),
                    (b'DE' , b'Germany' ),
                    (b'GH' , b'Ghana' ),
                    (b'GI' , b'Gibraltar' ),
                    (b'GR' , b'Greece' ),
                    (b'GL' , b'Greenland' ),
                    (b'GD' , b'Grenada' ),
                    (b'GP' , b'Guadeloupe' ),
                    (b'GU' , b'Guam' ),
                    (b'GT' , b'Guatemala' ),
                    (b'GG' , b'Guernsey' ),
                    (b'GN' , b'Guinea' ),
                    (b'GW' , b'Guinea-bissau' ),
                    (b'GY' , b'Guyana' ),
                    (b'HT' , b'Haiti' ),
                    (b'HM' , b'Heard Island and Mcdonald Islands' ),
                    (b'VA' , b'Vatican City State' ),
                    (b'HN' , b'Honduras' ),
                    (b'HK' , b'Hong Kong' ),
                    (b'HU' , b'Hungary' ),
                    (b'IS' , b'Iceland' ),
                    (b'IN' , b'India' ),
                    (b'ID' , b'Indonesia' ),
                    (b'IR' , b'Iran Islamic Republic of' ),
                    (b'IQ' , b'Iraq' ),
                    (b'IE' , b'Ireland' ),
                    (b'IM' , b'Isle of Man' ),
                    (b'IL' , b'Israel' ),
                    (b'IT' , b'Italy' ),
                    (b'JM' , b'Jamaica' ),
                    (b'JP' , b'Japan' ),
                    (b'JE' , b'Jersey' ),
                    (b'JO' , b'Jordan' ),
                    (b'KZ' , b'Kazakhstan' ),
                    (b'KE' , b'Kenya' ),
                    (b'KI' , b'Kiribati' ),
                    (b'KP' , b'Korea Democratic Peoples Republic of' ),
                    (b'KR' , b'Korea Republic of' ),
                    (b'KW' , b'Kuwait' ),
                    (b'KG' , b'Kyrgyzstan' ),
                    (b'LA' , b'Laos People Democratic Republic' ),
                    (b'LV' , b'Latvia' ),
                    (b'LB' , b'Lebanon' ),
                    (b'LS' , b'Lesotho' ),
                    (b'LR' , b'Liberia' ),
                    (b'LY' , b'Libyan Arab Jamahiriya' ),
                    (b'LI' , b'Liechtenstein' ),
                    (b'LT' , b'Lithuania' ),
                    (b'LU' , b'Luxembourg' ),
                    (b'MO' , b'Macao' ),
                    (b'MK' , b'Macedonia The Former Yugoslav Republic of' ),
                    (b'MG' , b'Madagascar' ),
                    (b'MW' , b'Malawi' ),
                    (b'MY' , b'Malaysia' ),
                    (b'MV' , b'Maldives' ),
                    (b'ML' , b'Mali' ),
                    (b'MT' , b'Malta' ),
                    (b'MH' , b'Marshall Islands' ),
                    (b'MQ' , b'Martinique' ),
                    (b'MR' , b'Mauritania' ),
                    (b'MU' , b'Mauritius' ),
                    (b'YT' , b'Mayotte' ),
                    (b'MX' , b'Mexico' ),
                    (b'FM' , b'Micronesia' ),
                    (b'MD' , b'Moldova' ),
                    (b'MC' , b'Monaco' ),
                    (b'MN' , b'Mongolia' ),
                    (b'ME' , b'Montenegro' ),
                    (b'MS' , b'Montserrat' ),
                    (b'MA' , b'Morocco' ),
                    (b'MZ' , b'Mozambique' ),
                    (b'MM' , b'Myanmar' ),
                    (b'NA' , b'Namibia' ),
                    (b'NR' , b'Nauru' ),
                    (b'NP' , b'Nepal' ),
                    (b'NL' , b'Netherlands' ),
                    (b'AN' , b'Netherlands Antilles' ),
                    (b'NC' , b'New Caledonia' ),
                    (b'NZ' , b'New Zealand' ),
                    (b'NI' , b'Nicaragua' ),
                    (b'NE' , b'Niger' ),
                    (b'NG' , b'Nigeria' ),
                    (b'NU' , b'Niue' ),
                    (b'NF' , b'Norfolk Island' ),
                    (b'MP' , b'Northern Mariana Islands' ),
                    (b'NO' , b'Norway' ),
                    (b'OM' , b'Oman' ),
                    (b'PK' , b'Pakistan' ),
                    (b'PW' , b'Palau' ),
                    (b'PS' , b'Palestinian Territory Occupied' ),
                    (b'PA' , b'Panama' ),
                    (b'PG' , b'Papua New Guinea' ),
                    (b'PY' , b'Paraguay' ),
                    (b'PE' , b'Peru' ),
                    (b'PH' , b'Philippines' ),
                    (b'PN' , b'Pitcairn' ),
                    (b'PL' , b'Poland' ),
                    (b'PT' , b'Portugal' ),
                    (b'PR' , b'Puerto Rico' ),
                    (b'QA' , b'Qatar' ),
                    (b'RE' , b'Reunion' ),
                    (b'RO' , b'Romania' ),
                    (b'RU' , b'Russian Federation' ),
                    (b'RW' , b'Rwanda' ),
                    (b'SH' , b'Saint Helena' ),
                    (b'KN' , b'Saint Kitts and Nevis' ),
                    (b'LC' , b'Saint Lucia' ),
                    (b'PM' , b'Saint Pierre and Miquelon' ),
                    (b'VC' , b'Saint Vincent and The Grenadines' ),
                    (b'WS' , b'Samoa' ),
                    (b'SM' , b'San Marino' ),
                    (b'ST' , b'Sao Tome and Principe' ),
                    (b'SA' , b'Saudi Arabia' ),
                    (b'SN' , b'Senegal' ),
                    (b'RS' , b'Serbia' ),
                    (b'SC' , b'Seychelles' ),
                    (b'SL' , b'Sierra Leone' ),
                    (b'SG' , b'Singapore' ),
                    (b'SK' , b'Slovakia' ),
                    (b'SI' , b'Slovenia' ),
                    (b'SB' , b'Solomon Islands' ),
                    (b'SO' , b'Somalia' ),
                    (b'ZA' , b'South Africa' ),
                    (b'GS' , b'South Georgia and The South Sandwich Islands' ),
                    (b'ES' , b'Spain' ),
                    (b'LK' , b'Sri Lanka' ),
                    (b'SD' , b'Sudan' ),
                    (b'SR' , b'Suriname' ),
                    (b'SJ' , b'Svalbard and Jan Mayen' ),
                    (b'SZ' , b'Swaziland' ),
                    (b'SE' , b'Sweden' ),
                    (b'CH' , b'Switzerland' ),
                    (b'SY' , b'Syrian Arab Republic' ),
                    (b'TW' , b'Taiwan Province of China' ),
                    (b'TJ' , b'Tajikistan' ),
                    (b'TZ' , b'Tanzania United Republic of' ),
                    (b'TH' , b'Thailand' ),
                    (b'TL' , b'Timor leste' ),
                    (b'TG' , b'Togo' ),
                    (b'TK' , b'Tokelau' ),
                    (b'TO' , b'Tonga' ),
                    (b'TT' , b'Trinidad and Tobago' ),
                    (b'TN' , b'Tunisia' ),
                    (b'TR' , b'Turkey' ),
                    (b'TM' , b'Turkmenistan' ),
                    (b'TC' , b'Turks and Caicos Islands' ),
                    (b'TV' , b'Tuvalu' ),
                    (b'UG' , b'Uganda' ),
                    (b'UA' , b'Ukraine' ),
                    (b'AE' , b'United Arab Emirates' ),
                    (b'GB' , b'United Kingdom' ),
                    (b'US' , b'United States' ),
                    (b'UM' , b'United States Minor Outlying Islands' ),
                    (b'UY' , b'Uruguay' ),
                    (b'UZ' , b'Uzbekistan' ),
                    (b'VU' , b'Vanuatu' ),
                    (b'VE' , b'Venezuela' ),
                    (b'VN' , b'Viet Nam' ),
                    (b'VG' , b'Virgin Islands British' ),
                    (b'VI' , b'Virgin Islands US' ),
                    (b'WF' , b'Wallis and Futuna' ),
                    (b'EH' , b'Western Sahara' ),
                    (b'YE' , b'Yemen' ),
                    (b'ZM' , b'Zambia' ),
                    (b'ZW' , b'Zimbabwe') ] )),
                ('age', models.CharField(verbose_name="Age", max_length=20)),
                ('phone_number', models.CharField(verbose_name="Phone Number", max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
