from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from custom_reg_form.models import ExtraInfo


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('consent', models.CharField(max_length=2000)),
                ('study_programme', models.CharField(max_length=2000)),
                ('enhanced_gender', models.CharField(max_length=2000)),
                ('current_semester_of_study', models.CharField(max_length=2000)),
                ('part_time_student', models.CharField(max_length=2000)),
                ('bachelor_level_statistics', models.CharField(max_length=2000)),
                ('master_level_statistics', models.CharField(max_length=2000)),
                ('familiar_with_R', models.CharField(max_length=2000)),
                ('importance_DAEI', models.CharField(max_length=2000)),
                ('motivation_DAEI', models.CharField(max_length=2000)),
                ('procrastinate', models.CharField(max_length=2000)),
                ('measure_self_set_goals', models.CharField(max_length=2000)),
                ('measure_around_you', models.CharField(max_length=2000)),
                ('more_time_on_course', models.CharField(max_length=2000)),
                ('course_how_many_students_studying', models.CharField(max_length=2000)),
                ('list_zp1', models.CharField(max_length=2000)),
                ('list_zp2', models.CharField(max_length=2000)),
                ('list_zp3', models.CharField(max_length=2000)),
                ('list_kon1', models.CharField(max_length=2000)),
                ('list_kon2', models.CharField(max_length=2000)),
                ('list_kon3', models.CharField(max_length=2000)),
                ('list_reg1', models.CharField(max_length=2000)),
                ('list_reg2', models.CharField(max_length=2000)),
                ('list_reg3', models.CharField(max_length=2000)),
                ('list_lang', models.CharField(max_length=2000)),
                ('scale_gradegoal1', models.CharField(max_length=2000)),
                ('scale_gradegoal2', models.CharField(max_length=2000)),
                ('your_age', models.CharField(max_length=2000)),
                ('scale_efficacy1', models.CharField(max_length=2000)),
                ('scale_efficacy2', models.CharField(max_length=2000)),
                ('scale_efficacy3', models.CharField(max_length=2000)),
                ('scale_efficacy4', models.CharField(max_length=2000)),
                ('scale_efficacy5', models.CharField(max_length=2000)),
                ('scale_efficacy6', models.CharField(max_length=2000)),
                ('scale_efficacy7', models.CharField(max_length=2000)),
                ('scale_efficacy8', models.CharField(max_length=2000)),
                ('scale_meta_cog1', models.CharField(max_length=2000)),
                ('scale_meta_cog2', models.CharField(max_length=2000)),
                ('scale_meta_cog3', models.CharField(max_length=2000)),
                ('scale_meta_cog4', models.CharField(max_length=2000)),
                ('scale_meta_cog5', models.CharField(max_length=2000)),
                ('scale_meta_cog6', models.CharField(max_length=2000)),
                ('scale_meta_cog7', models.CharField(max_length=2000)),
                ('scale_meta_cog8', models.CharField(max_length=2000)),
                ('scale_meta_cog9', models.CharField(max_length=2000)),
                ('scale_meta_cog10', models.CharField(max_length=2000)),
                ('scale_meta_cog11', models.CharField(max_length=2000)),
                ('scale_meta_cog12', models.CharField(max_length=2000)),
                ('scale_mnmgt_int1', models.CharField(max_length=2000)),
                ('scale_mnmgt_int2', models.CharField(max_length=2000)),
                ('scale_mnmgt_int3', models.CharField(max_length=2000)),
                ('scale_mnmgt_int4', models.CharField(max_length=2000)),
                ('scale_mnmgt_int5', models.CharField(max_length=2000)),
                ('scale_mnmgt_int6', models.CharField(max_length=2000)),
                ('scale_mnmgt_int7', models.CharField(max_length=2000)),
                ('scale_mnmgt_int8', models.CharField(max_length=2000)),
                ('scale_mnmgt_int9', models.CharField(max_length=2000)),
                ('scale_mnmgt_int10', models.CharField(max_length=2000)),
                ('scale_mnmgt_int11', models.CharField(max_length=2000)),
                ('scale_mnmgt_int12', models.CharField(max_length=2000)),
                ('scale_cog1', models.CharField(max_length=2000)),
                ('scale_cog2', models.CharField(max_length=2000)),
                ('scale_cog3', models.CharField(max_length=2000)),
                ('scale_cog4', models.CharField(max_length=2000)),
                ('scale_cog5', models.CharField(max_length=2000)),
                ('scale_cog6', models.CharField(max_length=2000)),
                ('scale_cog7', models.CharField(max_length=2000)),
                ('scale_cog8', models.CharField(max_length=2000)),
                ('scale_proc1', models.CharField(max_length=2000)),
                ('scale_proc2', models.CharField(max_length=2000)),
                ('scale_proc3', models.CharField(max_length=2000)),
                ('scale_proc4', models.CharField(max_length=2000)),
                ('scale_proc5', models.CharField(max_length=2000)),
                ('scale_big5_1', models.CharField(max_length=2000)),
                ('scale_big5_2', models.CharField(max_length=2000)),
                ('scale_anxiety1', models.CharField(max_length=2000)),
                ('scale_anxiety2', models.CharField(max_length=2000)),
                ('scale_anxiety3', models.CharField(max_length=2000)),
                ('scale_anxiety4', models.CharField(max_length=2000)),
                ('scale_anxiety5', models.CharField(max_length=2000)),

                ('user', models.OneToOneField(null=True, on_delete=models.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
